services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ml_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  trainer:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/app

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"

networks:
  default:
    name: mlops-net

volumes:
  pgdata: