stages:
  prepare:
    cmd: python src/prepare.py
    outs:
      - data/processed/data.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/data.csv
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - models/model.pkl
    metrics:
      - metrics/metrics.json